version: "3.8"

services:
  vite-app:
    build: .
    ports:
      - "3000:80"
    container_name: vite_app_container
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
      - NODE_ENV=development
